"""Run: python seed_mcq.py"""
from app import create_app
from app.extensions import db
from app.models.mcq import MCQQuestion

app = create_app()
with app.app_context():
    if MCQQuestion.query.count() > 0:
        print('MCQ questions already seeded')
        exit(0)

    questions = [
        # Python - Data Types
        MCQQuestion(topic='Python', subtopic='Data Types', points=10, difficulty='Easy',
            question='What is the output of type([]) in Python?',
            options=["<class 'list'>", "<class 'array'>", "<class 'tuple'>", "<class 'dict'>"],
            correct_answer=0,
            explanation="[] is a list literal. type([]) returns <class 'list'>."),
        MCQQuestion(topic='Python', subtopic='Data Types', points=10, difficulty='Easy',
            question='Which of the following is NOT a valid Python data type?',
            options=['int', 'float', 'char', 'str'],
            correct_answer=2,
            explanation="Python has no 'char' type. Single characters are strings of length 1."),
        MCQQuestion(topic='Python', subtopic='Data Types', points=10, difficulty='Medium',
            question='What is the result of: x = (1, 2, 3); x[1] = 5?',
            options=['x becomes (1, 5, 3)', 'x becomes (5, 2, 3)', 'TypeError', 'IndexError'],
            correct_answer=2,
            explanation='Tuples are immutable. Assigning to an index raises TypeError.'),
        MCQQuestion(topic='Python', subtopic='Data Types', points=10, difficulty='Easy',
            question='What does len("Hello World".split()) return?',
            options=['11', '2', '10', '1'],
            correct_answer=1,
            explanation='split() without args splits by whitespace. "Hello World" gives ["Hello","World"], len=2.'),
        # Python - Functions
        MCQQuestion(topic='Python', subtopic='Functions', points=10, difficulty='Easy',
            question='What keyword defines a function in Python?',
            options=['func', 'function', 'def', 'define'],
            correct_answer=2,
            explanation="Python uses 'def' to define functions."),
        MCQQuestion(topic='Python', subtopic='Functions', points=15, difficulty='Medium',
            question='What does *args allow in a function definition?',
            options=['Only keyword arguments', 'Variable positional arguments', 'A single tuple', 'Default values'],
            correct_answer=1,
            explanation='*args collects extra positional arguments into a tuple.'),
        MCQQuestion(topic='Python', subtopic='Functions', points=15, difficulty='Medium',
            question='What is the output of: def f(a, b=2): return a+b; print(f(3))?',
            options=['Error', '2', '5', '3'],
            correct_answer=2,
            explanation='b defaults to 2. f(3) returns 3+2=5.'),
        # Python - OOP
        MCQQuestion(topic='Python', subtopic='OOP', points=15, difficulty='Medium',
            question='Which method is called automatically when an object is created?',
            options=['__start__', '__new__', '__init__', '__create__'],
            correct_answer=2,
            explanation='__init__ is the constructor called on object creation.'),
        MCQQuestion(topic='Python', subtopic='OOP', points=20, difficulty='Hard',
            question='What is Method Resolution Order (MRO) used for?',
            options=['Memory management', 'Method lookup order in inheritance', 'Sorting methods alphabetically', 'None of the above'],
            correct_answer=1,
            explanation='MRO determines the order Python searches for methods in multiple inheritance.'),
        # SQL - SELECT
        MCQQuestion(topic='SQL', subtopic='SELECT Queries', points=10, difficulty='Easy',
            question='Which clause filters rows in SQL?',
            options=['HAVING', 'WHERE', 'FILTER', 'SELECT'],
            correct_answer=1,
            explanation='WHERE filters rows before grouping. HAVING filters after GROUP BY.'),
        MCQQuestion(topic='SQL', subtopic='SELECT Queries', points=10, difficulty='Easy',
            question='What does SELECT DISTINCT do?',
            options=['Returns NULL values', 'Returns unique rows', 'Returns the first row', 'Returns sorted rows'],
            correct_answer=1,
            explanation='DISTINCT eliminates duplicate rows from the result set.'),
        MCQQuestion(topic='SQL', subtopic='SELECT Queries', points=15, difficulty='Medium',
            question='What is the correct order of clauses in a SQL query?',
            options=['WHERE, SELECT, FROM', 'SELECT, FROM, WHERE', 'FROM, WHERE, SELECT', 'SELECT, WHERE, FROM'],
            correct_answer=1,
            explanation='Standard order: SELECT ... FROM ... WHERE ... GROUP BY ... HAVING ... ORDER BY'),
        # SQL - Joins
        MCQQuestion(topic='SQL', subtopic='Joins', points=15, difficulty='Medium',
            question='Which JOIN returns all rows from both tables with NULLs where no match?',
            options=['INNER JOIN', 'LEFT JOIN', 'FULL OUTER JOIN', 'CROSS JOIN'],
            correct_answer=2,
            explanation='FULL OUTER JOIN returns all rows from both tables, NULLs on non-matching side.'),
        MCQQuestion(topic='SQL', subtopic='Joins', points=15, difficulty='Medium',
            question='What does INNER JOIN return?',
            options=['All rows from left', 'All rows from right', 'Only matching rows from both', 'All rows from both'],
            correct_answer=2,
            explanation='INNER JOIN returns only rows where there is a match in both tables.'),
        # Aptitude
        MCQQuestion(topic='Aptitude', subtopic='Percentages', points=10, difficulty='Easy',
            question='What is 25% of 200?',
            options=['25', '50', '75', '100'],
            correct_answer=1,
            explanation='25/100 x 200 = 50.'),
        MCQQuestion(topic='Aptitude', subtopic='Percentages', points=15, difficulty='Medium',
            question='A price increases by 20% then decreases by 20%. The net change is?',
            options=['0%', '-4%', '+4%', '-2%'],
            correct_answer=1,
            explanation='100 -> 120 -> 96. Net = -4%.'),
        MCQQuestion(topic='Aptitude', subtopic='Time & Work', points=15, difficulty='Medium',
            question='A finishes work in 10 days, B in 15 days. How many days together?',
            options=['5 days', '6 days', '8 days', '12 days'],
            correct_answer=1,
            explanation='1/10 + 1/15 = 1/6. Together: 6 days.'),
        MCQQuestion(topic='Aptitude', subtopic='Time & Work', points=15, difficulty='Medium',
            question='A is twice as fast as B. If B takes 12 days, how long for A alone?',
            options=['6 days', '4 days', '8 days', '3 days'],
            correct_answer=0,
            explanation='A is twice as fast, so A takes 12/2 = 6 days.'),
        # Data Structures
        MCQQuestion(topic='Data Structures', subtopic='Arrays', points=10, difficulty='Easy',
            question='Time complexity of accessing an array element by index?',
            options=['O(n)', 'O(log n)', 'O(1)', 'O(n2)'],
            correct_answer=2,
            explanation='Array index access is O(1) — direct memory address calculation.'),
        MCQQuestion(topic='Data Structures', subtopic='Arrays', points=15, difficulty='Medium',
            question='Worst-case time complexity of linear search in an array of n elements?',
            options=['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
            correct_answer=2,
            explanation='Linear search checks each element — worst case O(n).'),
        MCQQuestion(topic='Data Structures', subtopic='Linked Lists', points=15, difficulty='Medium',
            question='Time complexity of inserting at the beginning of a singly linked list?',
            options=['O(n)', 'O(1)', 'O(log n)', 'O(n2)'],
            correct_answer=1,
            explanation='Updating the head pointer is O(1).'),
        MCQQuestion(topic='Data Structures', subtopic='Trees', points=15, difficulty='Medium',
            question='In a binary search tree, which traversal gives sorted output?',
            options=['Preorder', 'Postorder', 'Inorder', 'Level order'],
            correct_answer=2,
            explanation='Inorder traversal (left, root, right) of a BST gives elements in sorted order.'),
        # Verbal
        MCQQuestion(topic='Verbal', subtopic='Vocabulary', points=10, difficulty='Easy',
            question='What is the antonym of "benevolent"?',
            options=['Kind', 'Malevolent', 'Generous', 'Charitable'],
            correct_answer=1,
            explanation='Benevolent means kind/well-meaning. Malevolent means wishing harm.'),
        MCQQuestion(topic='Verbal', subtopic='Vocabulary', points=10, difficulty='Easy',
            question='What does "verbose" mean?',
            options=['Brief and concise', 'Using more words than needed', 'Silent', 'Clearly expressed'],
            correct_answer=1,
            explanation='Verbose means using or expressed in more words than are needed.'),
        MCQQuestion(topic='Verbal', subtopic='Grammar', points=10, difficulty='Easy',
            question='Which sentence is grammatically correct?',
            options=['He go to school', 'He goes to school', 'He going to school', 'He gone to school'],
            correct_answer=1,
            explanation='"He goes to school" uses correct subject-verb agreement for third person singular.'),
    ]

    for q in questions:
        db.session.add(q)
    db.session.commit()
    print(f'Seeded {len(questions)} MCQ questions successfully')
